name: dev CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev, master ]

jobs:
  g8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
    
      - uses: actions/setup-node@v4
        with:
            node-version: "22.15.0"
            registry-url: "https://registry.npmjs.org"
      - run: npm install -g npm@10.9.2

      - uses: coursier/setup-action@v1.2.0
        with:
          jvm: temurin:1.21
          apps: sbt sbtn giter8
      - uses: coursier/cache-action@v6.3

      - name: Cache ~/.npm
        uses: actions/cache@v4
        with:
            path: ~/.npm
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-node-

      - name: Extract branch name (Trigger - PR)
        if: github.event_name == 'pull_request'
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF})" >> $GITHUB_ENV

      - name: Extract branch name (Trigger - Push)
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
        id: extract_branch

      - name: create new project from esw-gateway-ui-template.g8 template
        run: |
          echo "Running build for branch ${BRANCH_NAME}"
          g8 tmtsoftware/esw-gateway-ui-template.g8 --project_name=ui-app --branch ${BRANCH_NAME}

      - name: Build - UI app
        working-directory: ./ui-app
        run: |
            npm install
            npm run build
            npm run test

      - name: Notify slack
        if: always()
        continue-on-error: true
        uses: kpritam/slack-job-status-action@v1
        with:
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: ci-dev

