name: release

on:
  push:
    tags:
      - "v*"
    branches: [ master ]

jobs:
  g8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
            node-version: "22.15.0"
            registry-url: "https://registry.npmjs.org"
      - run: npm install -g npm@10.9.2

      - name: Cache ~/.npm
        uses: actions/cache@v4
        with:
            path: ~/.npm
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-node-

      - uses: coursier/setup-action@v1.2.0
        with:
          jvm: temurin:1.21
          apps: sbt sbtn giter8
      - uses: coursier/cache-action@v6.3

      - name: create new project from esw-gateway-ui-template.g8 template with specified version
        run: |
            g8 tmtsoftware/esw-gateway-ui-template.g8 --project_name=ui-app

      - name: Build - UI app
        working-directory: ./ui-app
        run: |
            npm install
            npm run build
            npm run test

      - name: Notify slack
        if: always()
        continue-on-error: true
        uses: kpritam/slack-job-status-action@v1
        with:
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: ci-release
